// This file was generated by silverstripe/cow from client/lang/src/en.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('en', {
    "MultiFactorAuthentication.HOW_MFA_WORKS": "How multi-factor authentication works",
    "MultiFactorAuthentication.TITLE": "Add extra security to your account",
    "MultiFactorAuthentication.HOW_IT_WORKS": "How it works",
    "MultiFactorAuthentication.EXTRA_LAYER_IMAGE_ALT": "Shields indicating additional protection",
    "MultiFactorAuthentication.EXTRA_LAYER_TITLE": "Extra layer of protection",
    "MultiFactorAuthentication.EXTRA_LAYER_DESCRIPTION": "Every time you log into your account, you'll need your password and an additional form of verification.",
    "MultiFactorAuthentication.UNIQUE_IMAGE_ALT": "Person with tick indicating uniqueness",
    "MultiFactorAuthentication.UNIQUE_TITLE": "Unique to you",
    "MultiFactorAuthentication.UNIQUE_DESCRIPTION": "This verification is only available to you. Even if someone gets your password, they will not be able to access your account.",
    "MultiFactorAuthentication.GET_STARTED": "Get started",
    "MultiFactorAuthentication.SETUP_LATER": "Setup later",
    "MultiFactorAuthentication.ADD_ANOTHER_METHOD": "Add another MFA method",
    "MultiFactorAuthentication.ADD_FIRST_METHOD": "Add an MFA method",
    "MultiFactorAuthentication.REGISTERED": "{method}: Registered",
    "MultiFactorAuthentication.DEFAULT_REGISTERED": "{method} (default): Registered",
    "MultiFactorAuthentication.BACKUP_REGISTERED": "{method}: Created {date}",
    "MultiFactorAuthentication.RESET_METHOD": "Reset",
    "MultiFactorAuthentication.REMOVE_METHOD": "Remove",
    "MultiFactorAuthentication.SET_AS_DEFAULT": "Set as default method",
    "MultiFactorAuthentication.NO_METHODS_REGISTERED": "No MFA methods have been registered. Add one using the button below",
    "MultiFactorAuthentication.NO_METHODS_REGISTERED_READONLY": "This member has not registered any MFA methods yet",
    "MultiFactorAuthentication.SELECT_METHOD": "Select a verification method",
    "MultiFactorAuthentication.SETUP_COMPLETE_TITLE": "Multi-factor authentication is now set up",
    "MultiFactorAuthentication.ACCOUNT_RESET_TITLE": "Help user reset account",
    "MultiFactorAuthentication.ACCOUNT_RESET_DESCRIPTION": "Ensure that the person requesting a reset is the real person associated with this account before proceeding. An email will be sent to the member's address with a link to reset both their password and multi-factor authentication methods.",
    "MultiFactorAuthentication.ACCOUNT_RESET_ACTION": "Send account reset email",
    "MultiFactorAuthentication.ACCOUNT_RESET_SENDING": "Sending...",
    "MultiFactorAuthentication.ACCOUNT_RESET_SENDING_SUCCESS": "An email has been sent.",
    "MultiFactorAuthentication.ACCOUNT_RESET_SENDING_FAILURE": "We were unable to send an email, please try again later.",
    "MultiFactorAuthentication.ACCOUNT_RESET_CONFIRMATION": "You are about to reset this account. Their password and multi-factor authentication will be reset. Continue?",
    "MultiFactorAuthentication.ACCOUNT_RESET_CONFIRMATION_BUTTON": "Yes, send reset email",
    "MultiFactorAuthentication.DEFAULT_CONFIRM_BUTTON": "Confirm",
    "MultiFactorAuthentication.DEFAULT_CONFIRM_DISMISS_BUTTON": "Cancel",
    "MultiFactorAuthentication.DELETE_CONFIRMATION": "Are you sure you want to remove this method",
    "MultiFactorAuthentication.CONFIRMATION_TITLE": "Are you sure?",
    "MultiFactorAuthentication.DELETE_CONFIRMATION_BUTTON": "Remove method",
    "MultiFactorAuthentication.RESET_BACKUP_CONFIRMATION": "All existing codes will be made invalid and new codes will be created",
    "MultiFactorAuthentication.RESET_BACKUP_CONFIRMATION_BUTTON": "Reset codes",
    "MultiFactorAuthentication.ADMIN_SETUP_COMPLETE_CONTINUE": "Your settings have been updated",
    "MultiFactorAuthentication.TRY_AGAIN_ERROR": "Something went wrong. Please try again.",
    "MultiFactorAuthentication.UNKNOWN_ERROR": "An unknown error occurred."
});
}