// This file was generated by silverstripe/tx-translator from client/lang/src/sv.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sv', {
    "MultiFactorAuthentication.HOW_MFA_WORKS": "Hur multifaktorautentisering fungerar",
    "MultiFactorAuthentication.TITLE": "Lägg till extra säkerhet till ditt konto",
    "MultiFactorAuthentication.HOW_IT_WORKS": "Hur det fungerar",
    "MultiFactorAuthentication.EXTRA_LAYER_IMAGE_ALT": "Sköldar som indikerar extra skydd",
    "MultiFactorAuthentication.EXTRA_LAYER_TITLE": "Extra lager av skydd",
    "MultiFactorAuthentication.EXTRA_LAYER_DESCRIPTION": "Varje gång du loggar in på ditt konto behöver du ditt lösenord och en ytterligare form av verifiering.",
    "MultiFactorAuthentication.UNIQUE_IMAGE_ALT": "Person med bock som indikerar unikhet",
    "MultiFactorAuthentication.UNIQUE_TITLE": "Unik till dig",
    "MultiFactorAuthentication.UNIQUE_DESCRIPTION": "Denna verifikation är endast tillgänglig för dig. Även fast någon får tillgång till ditt lösenord har de ej tillgång till ditt konto.",
    "MultiFactorAuthentication.GET_STARTED": "Kom igång",
    "MultiFactorAuthentication.SETUP_LATER": "Konfigurera senare",
    "MultiFactorAuthentication.ADD_ANOTHER_METHOD": "Lägg till en ny MFA metod",
    "MultiFactorAuthentication.ADD_FIRST_METHOD": "Lägg till en MFA metod",
    "MultiFactorAuthentication.REGISTERED": "{method}: Registrerad",
    "MultiFactorAuthentication.DEFAULT_REGISTERED": "{method} (default): Registrerad",
    "MultiFactorAuthentication.BACKUP_REGISTERED": "{method}: Skapad {date}",
    "MultiFactorAuthentication.RESET_METHOD": "Återställ",
    "MultiFactorAuthentication.REMOVE_METHOD": "Radera",
    "MultiFactorAuthentication.SET_AS_DEFAULT": "Välj som standardmetod",
    "MultiFactorAuthentication.NO_METHODS_REGISTERED": "Inga MFA metoder är registrerade. Lägg till en genom att trycka på knappen nedan",
    "MultiFactorAuthentication.NO_METHODS_REGISTERED_READONLY": "Detta konto har inga registrerade MFA metoder ännu",
    "MultiFactorAuthentication.SELECT_METHOD": "Välj verifikationsmetod",
    "MultiFactorAuthentication.SETUP_COMPLETE_TITLE": "Multifaktorautentisering är nu konfigurerad",
    "MultiFactorAuthentication.ACCOUNT_RESET_TITLE": "Hjälp användaren att återställa sitt konto",
    "MultiFactorAuthentication.ACCOUNT_RESET_DESCRIPTION": "Se till att personen som begär återställningen är den verkliga personen som är kopplad till det här kontot innan du fortsätter. Ett e-postmeddelande kommer att skickas till medlemmens e-postaddress med en länk för att återställa både deras lösenord och multifaktorautentiseringsmetoder.",
    "MultiFactorAuthentication.ACCOUNT_RESET_ACTION": "Skicka återställningsmeddelande till kontot",
    "MultiFactorAuthentication.ACCOUNT_RESET_SENDING": "Skickar...",
    "MultiFactorAuthentication.ACCOUNT_RESET_SENDING_SUCCESS": "Ett e-postmeddelande har skickats.",
    "MultiFactorAuthentication.ACCOUNT_RESET_SENDING_FAILURE": "Vi kunde inte skicka ett e-postmeddelande, vänligen försök igen senare.",
    "MultiFactorAuthentication.ACCOUNT_RESET_CONFIRMATION": "Du håller på att återställa detta konto. Deras lösenord och multifaktorautentisering kommer att återställas. Vill du fortsätta?",
    "MultiFactorAuthentication.ACCOUNT_RESET_CONFIRMATION_BUTTON": "Ja, skicka återställningsmail",
    "MultiFactorAuthentication.DEFAULT_CONFIRM_BUTTON": "Bekräfta",
    "MultiFactorAuthentication.DEFAULT_CONFIRM_DISMISS_BUTTON": "Avbryt",
    "MultiFactorAuthentication.DELETE_CONFIRMATION": "Är du säker att du vill ta bort denna metod?",
    "MultiFactorAuthentication.CONFIRMATION_TITLE": "Är du säker?",
    "MultiFactorAuthentication.DELETE_CONFIRMATION_BUTTON": "Ta bort metod",
    "MultiFactorAuthentication.RESET_BACKUP_CONFIRMATION": "Alla befintliga koder kommer bli ogiltiga och nya koder kommer att skapas",
    "MultiFactorAuthentication.RESET_BACKUP_CONFIRMATION_BUTTON": "Återställ koder",
    "MultiFactorAuthentication.ADMIN_SETUP_COMPLETE_CONTINUE": "Dina inställningar har uppdaterats.",
    "MultiFactorAuthentication.TRY_AGAIN_ERROR": "Något gick fel. Vänligen försök igen.",
    "MultiFactorAuthentication.UNKNOWN_ERROR": "Ett okänt fel uppstod."
});
}