---
Name: mfalogging
---
Injector:
  # Note: bring your own handlers, none are configured by default
  Psr\Log\LoggerInterface.mfa:
    type: singleton
    class: Monolog\Logger
    constructor:
      - 'mfa-log'

  SilverStripe\Dev\State\SapphireTestState:
    properties:
      States:
        mfalogging: '%$SilverStripe\MFA\Dev\State\LoggerTestState'
