<?php

namespace Firesphere\BootstrapMFA\Tests;

use Firesphere\BootstrapMFA\Authenticators\BootstrapMFAAuthenticator;
use Firesphere\BootstrapMFA\Models\BackupCode;
use SilverStripe\Control\Controller;
use SilverStripe\Core\Injector\Injector;
use SilverStripe\Dev\SapphireTest;
use SilverStripe\ORM\ValidationResult;
use SilverStripe\Security\IdentityStore;
use SilverStripe\Security\Member;
use SilverStripe\Control\Session;
use SilverStripe\Dev\Debug;

class BootstrapMFAAuthenticatorTest extends SapphireTest
{
    /**
     * @var BootstrapMFAAuthenticator
     */
    protected $authenticator;

    protected static $fixture_file = '../fixtures/member.yml';

    protected function setUp()
    {
        $this->authenticator = Injector::inst()->get(BootstrapMFAAuthenticator::class);
        return parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * Test if user codes are properly validated and expired
     *
     * @throws \Psr\Container\NotFoundExceptionInterface
     * @throws \SilverStripe\ORM\ValidationException
     * @throws \SilverStripe\Security\PasswordEncryptor_NotFoundException
     */
    public function testValidateBackupCodeRight()
    {
        /** @var Member $member */
        $member = $this->objFromFixture(Member::class, 'member1');
        Injector::inst()->get(IdentityStore::class)->logIn($member);
        $codes = BackupCode::generateTokensForMember($member);

        // Funky stuff, extract the codes from the session message
        /** @var Session $session */
        $session = Controller::curr()->getRequest()->getSession();

        $message = $session->get('token');

        $message = str_replace('<p>Here are your tokens, please store them securily. ' .
            'They are stored encrypted and can not be recovered, only reset.</p><p>', '', $message);
        $codes = explode('<br />', $message);

        // Actual testing
        foreach ($codes as $code) {
            $code = str_replace('</p>', '', $code);
            // The last item in the array is the </p>, which we don't want to test
            if ($code !== '') {
                $result = $this->authenticator->validateBackupCode($member, $code, $result);
                // All codes should be valid
                $this->assertTrue($result->isValid());
                $this->assertInstanceOf(Member::class, $result);

                $encryptedCode = $member->encryptWithUserSettings($code);

                $code = BackupCode::get()->filter(['Code' => $code])->first();
                $this->assertTrue($code->Used);
            }
        }
    }

    public function testValidateBackupCodeWrong()
    {
        $member = $this->objFromFixture(Member::class, 'member1');

        $this->authenticator->validateBackupCode($member, '12345', $result);

        $this->assertInstanceOf(ValidationResult::class, $result);
        $this->assertFalse($result->isValid());
    }
}