<?php

namespace Firesphere\BootstrapMFA\Tests;

use Firesphere\BootstrapMFA\Authenticators\BootstrapMFAAuthenticator;
use Firesphere\BootstrapMFA\Forms\MFALoginForm;
use Firesphere\BootstrapMFA\Handlers\MFALoginHandler;
use Firesphere\BootstrapMFA\Models\BackupCode;
use Firesphere\BootstrapMFA\Tests\Helpers\CodeHelper;
use Firesphere\BootstrapMFA\Tests\Mock\MockMFAHandler;
use SilverStripe\Control\Controller;
use SilverStripe\Control\Session;
use SilverStripe\Core\Injector\Injector;
use SilverStripe\Dev\Debug;
use SilverStripe\Dev\SapphireTest;
use SilverStripe\Security\Member;
use SilverStripe\Security\Security;

class MFALoginHandlerTest extends SapphireTest
{
    protected $request;

    protected $member;

    /**
     * @var BootstrapMFAAuthenticator
     */
    protected $authenticator;

    /**
     * @var MFALoginForm
     */
    protected $form;

    /**
     * @var MockMFAHandler
     */
    protected $handler;

    protected static $fixture_file = '../fixtures/member.yml';

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->request = Controller::curr()->getRequest();
        $this->member = $this->objFromFixture(Member::class, 'member1');

        $session = $this->request->getSession();
        $session->set('MFALogin.MemberID', $this->member->ID);

        $this->authenticator = Injector::inst()->create(BootstrapMFAAuthenticator::class);
        $this->form = Injector::inst()->createWithArgs(MFALoginForm::class, [Controller::curr(), $this->authenticator, 'test']);
        $this->handler = Injector::inst()->createWithArgs(MockMFAHandler::class, ['login', $this->authenticator]);
    }

    public function testSuccessValidate()
    {
        Security::setCurrentUser($this->member);
        BackupCode::generateTokensForMember($this->member);
        $tokens = CodeHelper::getCodesFromSession();
        $data = ['token' => $tokens[0]];
        $response = $this->handler->validate($data, $this->form, $this->request);

        $this->assertInstanceOf(Member::class, $response);
    }

    public function testErrorValidate()
    {
        $data = ['token' => 'wrongtokenforsure'];
        $response = $this->handler->validate($data, $this->form, $this->request);

        $this->assertFalse($response);
    }
}